name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@1f401f745bf57e30b3a2800ad308a87d2ebdf14b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
      - name: Install yq
        run: |
          sudo snap install yq
      - uses: actions/download-artifact@v3
        with:
          name: rock
      - name: Import and push to github package
        run: |
          rock_files=$(ls *.rock)
          for rock_file in $rock_files; do
              rockname=$(echo $rock_file | cut -d"_" -f1)
              image_name="$(yq '.name' rocks/$rockname/rockcraft.yaml)"
              version="$(yq '.version' rocks/$rockname/rockcraft.yaml)"
              sudo skopeo \
                --insecure-policy \
                copy \
                oci-archive:"${rock_file}" \
                docker-daemon:"ghcr.io/canonical/${image_name}:${version}"
              echo "Publishing rock ${image_name}:${version}"
              docker push ghcr.io/canonical/${image_name}:${version}
          done
