name: Publish all ROCKs from selected branch

on:
  workflow_dispatch:
    inputs:
      filter:
        description: Build/publish only matching ROCKs
        required: false
        default: ''
        type: string


jobs:
  allrocks:
    runs-on: ubuntu-latest
    outputs:
      rocks: ${{ steps.all-rocks.outputs.rocks }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: List rockcraft files
        id: list-files
        run: |
          find rocks -name rockcraft.yaml -print0 > rock-files.list
      - name: set output
        id: all-rocks
        env:
          FILTER: ${{ inputs.filter }}
        run: |
          set -euo pipefail
          components=()
          while IFS= read -r -d '' file; do
            component=${file#rocks/}
            component=${component%/rockcraft.yaml}
            components+=("${component}")
          done < rock-files.list
          all_rocks=$(jq --compact-output --null-input --arg filter "${FILTER}" \
            '$ARGS.positional | map(select(test($filter)))' \
            --args "${components[@]}")
          echo "All rocks: $all_rocks"
          echo "rocks=$all_rocks" >> "$GITHUB_OUTPUT"
  build-and-publish:
    needs: allrocks
    if: ${{ needs.allrocks.outputs.rocks != '[]' }}
    permissions:
      actions: read
      contents: write
      packages: write
    uses: ./.github/workflows/build_publish.yaml
    with:
      rocks: ${{ needs.allrocks.outputs.rocks }}
      publish: true
    secrets: inherit
